### ISSUE TITLE
Implement full-width conversation view option

### ISSUE THREAD

**Issue by NeeRaj-2401** [itsmartashub/GPThemes#1]
### Prerequisites (Required)

- [X] I [searched for any existing report](https://github.com/itsmartashub/GPThemes/issues?q=is%3Aissue) about this feature to avoid opening a duplicate.
- [X] This issue contains only one feature.
- [X] The title of this issue accurately describes the feature.

### Feature Request Description (Required)

the entire chat section is bounded within a container with certain width, utilise maximum available width,

### Screenshots or Videos (Optional)

current :
![image](https://github.com/itsmartashub/GPThemes/assets/88180887/a774e894-07cb-4874-acd5-36b55afa87e1)

desired :
![image](https://github.com/itsmartashub/GPThemes/assets/88180887/0d799671-5f15-4c22-bd1b-7729d312d9de)

**Comment by itsmartashub** [comment]
Thank you for your enthusiasm for enhancing GPThemes.

Could you share the reasoning behind your interest in this feature? Currently, on tablets and smaller screen devices, the chat bubbles already occupy the full available width. Are you proposing to extend this change to all screen sizes?

Let's consider why we should be cautious about implementing this proposal:

1. **Readability**: Even if the text doesn't cause horizontal scrolling because it fits within the viewport, longer lines of text can still impact readability. It's generally recommended to keep line lengths within a certain range to ensure comfortable reading. Maintaining a narrower chat container optimizes readability, ensuring effortless engagement.

2. **User Focus**: A narrower chat container aids users in staying focused on the conversation, reducing distractions from wide text blocks.

A better understanding of the use case will help to tailor the approach accordingly.

**Comment by NeeRaj-2401** [comment]
One thing which made me to think about utilizing the available width is when gpt generate codes and sometimes codes lines overflow the codeblock and we have to scroll horizontally to review  :)

And the other reason is I personally use GPT with sidebar closed ( thanks to their handy keybindings ). so in that case i feel like the chat bubbles should occupy a little more width

**with 100% page zoom :** 
<img src="https://github.com/itsmartashub/GPThemes/assets/88180887/23a03ba8-f7ac-47b0-b583-a9f6717e0a52" width="30%">

**with 80% page zoom (my browser default):**
<img src="https://github.com/itsmartashub/GPThemes/assets/88180887/1badf823-b71d-4e97-9c73-cd2b28af8d76" width="30%">

**Comment by itsmartashub** [comment]
Ah, I see. Thanks for the clarification, I now better understand the scenario where your suggestion makes sense. I agree that the somewhat restricted code block section is a bit irritating in this context. Increasing the maximum width of the chat bubble makes sense when the sidebar is hidden. I plan to add custom styling for some elements in the future, so perhaps I could include the chat bubble width in that.

**Comment by NeeRaj-2401** [comment]
Hi @itsmartashub , hope u r doing well, i wanted to mention that, now we do have a little bit of customisation options like themes and fonts, so its possible to include adjusting width container from those options itself

**Comment by itsmartashub** [comment]
Hi there @NeeRaj-2401. Telepathy, cause I just started working on this today. For now, it's a toggle for full width, but in the future I plan to make this option more customizable, allowing the user to choose the width percentage. 

- Also, which layout do you have, the old UI or the new one?
- And would you like the prompt field to be synchronized with the width of the chats, so that if the chats are full width, the prompt field is also full width or you would prefer it to stay at the default width?

**Comment by NeeRaj-2401** [comment]
> * Also, which layout do you have, the old UI or the new one?

New one

> * so that if the chats are full width, the prompt field is also full width or you would prefer it to stay at the default width?

I think the prompt field is ok as it is right now, but u know the design better than me 😅

> Just be aware that in the **new UI**, I can't make the **user chat** `100%` width **for now** because it causes the **edit icon** to disappear/cut off, which is unacceptable for UX, ofc

Yeah it makes sense 

> I would like to hear from you what could be improved.

Sure i will give it a try and let you know if there will be any further suggestions from my side, thanks :)
