### ISSUE TITLE
Fix language dropdown accessibility and styling issues

### ISSUE THREAD

**Issue by itsmartashub** [itsmartashub/GPThemes#72]
- The language elements (e.g. language dropdown, language active item) are currently not accessible due to z-indexing issues, causing them to be overlapped by other elements.
- Additionally, the styling of these elements does not match the theme, resulting in an inconsistent user experience.

---

- [x] Change `z-index` of all elements and test it
- [x] Refactor context menus (`[role='listbox']`, `[role='menu']`, `[role='option']`, `[role='menuitem']`) styles to make it more global
- [x] TEST THIS AT THE END! Could break many context menus, popovers and list elements

**Comment by lattaai4** [comment]
Hello, I tried to fix the issue

This is what I did:

Updated z-index values for language dropdown and refactored context menu styles to improve consistency and accessibility.

I also created pull request: https://github.com/itsmartashub/GPThemes/pull/73


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.
