### ISSUE TITLE
Prompt field: fix delayed styles application on page load

### ISSUE THREAD

**Issue by itsmartashub** [itsmartashub/GPThemes#74]
### Description
The background and submit button icon styles for the prompt textarea are currently being applied with a delay on page load. This causes a brief period where the textarea appears without the correct styling, resulting in a poor user experience.

### Steps to Reproduce:
1. Load the page containing the prompt textarea.
2. Observe the textarea's background and icon styles.
3. Note the brief delay before the styles are fully applied.

### Expected Behavior:
The prompt textarea styles should be applied immediately on page load.

### Cause:
The delay is likely caused by the targeting CSS element that is not rendered yet.

### Fix:
Target the `#prompt-textarea ` via `#composition-background` and ensure that the styles are applied correctly.

**Comment by lattaai5** [comment]
Hello, I tried to fix the issue

This is what I did:

Modified the CSS selectors to target #composer-background instead of relying on classes that might not be immediately available. This should apply the styles immediately on page load, fixing the delay issue.

I also created pull request: https://github.com/itsmartashub/GPThemes/pull/76


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.
